In [1]:
import pandas as pd

In [32]:
df = pd.read_csv('../../data/raw/TESS_TOI_2025.10.04_12.41.47.csv')
df.head()  # Muestra las primeras filas para verificar la carga

,toi,tid,tfopwg_disp,rastr,ra,decstr,dec,st_pmra,st_pmraerr1,st_pmraerr2,st_pmralim,st_pmdec,st_pmdecerr1,st_pmdecerr2,st_pmdeclim,pl_tranmid,pl_tranmiderr1,pl_tranmiderr2,pl_tranmidlim,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_trandurh,pl_trandurherr1,pl_trandurherr2,pl_trandurhlim,pl_trandep,pl_trandeperr1,pl_trandeperr2,pl_trandeplim,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,pl_insol,pl_insolerr1,pl_insolerr2,pl_insollim,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtlim,st_tmag,st_tmagerr1,st_tmagerr2,st_tmaglim,st_dist,st_disterr1,st_disterr2,st_distlim,st_teff,st_tefferr1,st_tefferr2,st_tefflim,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_rad,st_raderr1,st_raderr2,st_radlim,toi_created,rowupdate
0,1000.01,50365310,FP,07h29m25.85s,112.357708,-12d41m45.46s,-12.695960,-5.964,0.085,-0.085,0.0,-0.076,0.072,-0.072,0.0,2459229.630,0.001657,-0.001657,0,2.171348,0.000264,-0.000264,0,2.01722,0.319588,-0.319588,0,656.886099,37.778210,-37.778210,0,5.818163,1.910546,-1.910546,0,22601.94858,NaN,NaN,NaN,3127.204052,NaN,NaN,NaN,9.604000,0.013,-0.013,0,485.735,11.9515,-11.9515,0,10249.0,264.7,-264.7,0,4.19,0.07,-0.07,0,2.16986,0.072573,-0.072573,0,24/07/2019 15:58,09/09/2024 10:08
1,1001.01,88863718,PC,08h10m19.31s,122.580465,-05d30m49.87s,-5.513852,-4.956,0.102,-0.102,0.0,-15.555,0.072,-0.072,0.0,2459987.949,0.001916,-0.001916,0,1.931646,0.000005,-0.000005,0,3.16600,0.647000,-0.647000,0,1286.000000,1186.490000,-1186.490000,0,11.215400,2.624200,-2.624200,0,44464.50000,NaN,NaN,NaN,4045.000000,NaN,NaN,NaN,9.423440,0.006,-0.006,0,295.862,5.9100,-5.9100,0,7070.0,126.4,-126.4,0,4.03,0.09,-0.09,0,2.01000,0.090000,-0.090000,0,24/07/2019 15:58,03/04/2023 14:31
2,1002.01,124709665,FP,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,-1.462,0.206,-0.206,0.0,-2.249,0.206,-0.206,0.0,2459224.688,0.000625,-0.000625,0,1.867557,0.000003,-0.000003,0,1.40800,0.184000,-0.184000,0,1500.000000,1.758400,-1.758400,0,23.752900,NaN,NaN,0,2860.61000,NaN,NaN,NaN,2037.000000,NaN,NaN,NaN,9.299501,0.058,-0.058,0,943.109,106.3330,-106.3330,0,8924.0,124.0,-124.0,0,NaN,NaN,NaN,0,5.73000,NaN,NaN,0,24/07/2019 15:58,11/07/2022 16:02
3,1003.01,106997505,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,-0.939,0.041,-0.041,0.0,1.640,0.055,-0.055,0.0,2458493.396,0.005350,-0.005350,0,2.743230,0.001080,-0.001080,0,3.16700,0.642000,-0.642000,0,383.410000,0.781988,-0.781988,0,NaN,NaN,NaN,0,1177.36000,NaN,NaN,NaN,1631.000000,NaN,NaN,NaN,9.300300,0.037,-0.037,0,7728.170,1899.5700,-1899.5700,0,5388.5,567.0,-567.0,0,4.15,1.64,-1.64,0,NaN,NaN,NaN,0,24/07/2019 15:58,23/02/2022 10:10
4,1004.01,238597883,FP,08h08m42.77s,122.178195,-48d48m10.12s,-48.802811,-4.496,0.069,-0.069,0.0,9.347,0.062,-0.062,0.0,2459987.047,0.003748,-0.003748,0,3.573014,0.000013,-0.000013,0,3.37000,1.029000,-1.029000,0,755.000000,1306.550000,-1306.550000,0,11.311300,3.247140,-3.247140,0,54679.30000,NaN,NaN,NaN,4260.000000,NaN,NaN,NaN,9.135500,0.006,-0.006,0,356.437,4.6175,-4.6175,0,9219.0,171.1,-171.1,0,4.14,0.07,-0.07,0,2.15000,0.060000,-0.060000,0,24/07/2019 15:58,09/09/2024 10:08

In [ ]:
df.shape # Muestra la cantidad de filas y columnas del DataFrame

(7703, 65)

In [ ]:
df.isnull().sum() # Muestra la cantidad de valores nulos por columna

toi                   0
tid                   0
tfopwg_disp           0
rastr                 0
ra                    0
decstr                0
dec                   0
st_pmra             134
st_pmraerr1         134
st_pmraerr2         134
st_pmralim          134
st_pmdec            134
st_pmdecerr1        134
st_pmdecerr2        134
st_pmdeclim         134
pl_tranmid            0
pl_tranmiderr1       11
pl_tranmiderr2       11
pl_tranmidlim         0
pl_orbper           107
pl_orbpererr1       131
pl_orbpererr2       131
pl_orbperlim          0
pl_trandurh           0
pl_trandurherr1      13
pl_trandurherr2      13
pl_trandurhlim        0
pl_trandep            0
pl_trandeperr1        6
pl_trandeperr2        6
pl_trandeplim         0
pl_rade             506
pl_radeerr1        1623
pl_radeerr2        1623
pl_radelim            0
pl_insol            176
pl_insolerr1       7703
pl_insolerr2       7703
pl_insollim        7703
pl_eqt              311
pl_eqterr1         7703
pl_eqterr2         7703
pl_eqtlim          7703
st_tmag               0
st_tmagerr1           0
st_tmagerr2           0
st_tmaglim            0
st_dist             215
st_disterr1         707
st_disterr2         707
st_distlim            0
st_teff             161
st_tefferr1         474
st_tefferr2         474
st_tefflim            0
st_logg             856
st_loggerr1        2271
st_loggerr2        2271
st_logglim            0
st_rad              507
st_raderr1         1963
st_raderr2         1963
st_radlim             0
toi_created           0
rowupdate             0
dtype: int64

In [ ]:
df[df.st_raderr1.isnull()] # Muestra las filas donde 'st_raderr1' es nulo

,toi,tid,tfopwg_disp,rastr,ra,decstr,dec,st_pmra,st_pmraerr1,st_pmraerr2,...,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_rad,st_raderr1,st_raderr2,st_radlim,toi_created,rowupdate
2,1002.01,124709665,FP,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,-1.462,0.206,-0.206,...,NaN,NaN,NaN,0,5.7300,NaN,NaN,0,24/07/2019 15:58,11/07/2022 16:02
3,1003.01,106997505,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,-0.939,0.041,-0.041,...,4.15,1.64,-1.64,0,NaN,NaN,NaN,0,24/07/2019 15:58,23/02/2022 10:10
8,1008.01,440801822,FP,07h17m31.88s,109.382839,+13d23m42.79s,13.395219,-17.900,1.100,-1.100,...,4.20,1.90,-1.90,0,1.5700,NaN,NaN,0,24/07/2019 15:58,08/12/2023 16:02
9,1009.01,107782586,PC,07h26m40.28s,111.667845,-24d27m43.6s,-24.462111,-3.297,0.319,-0.319,...,NaN,NaN,NaN,0,NaN,NaN,NaN,0,24/07/2019 15:58,17/01/2024 10:08
11,1010.01,139853601,FP,07h29m10.56s,112.293981,-21d49m58.48s,-21.832912,-5.746,0.176,-0.176,...,NaN,NaN,NaN,0,1.0000,NaN,NaN,0,24/07/2019 15:58,29/10/2021 12:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679,976.01,347098457,FP,07h49m52.86s,117.470237,-16d01m24.29s,-16.023413,-1.507,0.045,-0.045,...,NaN,NaN,NaN,0,49.1612,NaN,NaN,0,24/07/2019 15:58,29/10/2021 12:59
7686,983.01,148659924,FP,07h39m27.46s,114.864422,-32d54m13.51s,-32.903754,-5.117,0.060,-0.060,...,4.08,1.26,-1.26,0,NaN,NaN,NaN,0,24/07/2019 15:58,08/03/2023 10:10
7695,992.01,108835813,FP,07h30m28.01s,112.616704,-26d04m50.46s,-26.080682,-2.927,0.061,-0.061,...,NaN,NaN,NaN,0,NaN,NaN,NaN,0,24/07/2019 15:58,29/10/2021 12:59
7698,995.01,317951248,FP,07h23m14.75s,110.811443,+05d33m46.26s,5.562850,2.061,0.405,-0.405,...,NaN,NaN,NaN,0,NaN,NaN,NaN,0,24/07/2019 15:58,29/10/2021 12:59
7699,996.01,142918609,FP,07h57m23.99s,119.349948,-19d30m57.65s,-19.516015,-3.900,0.848,-0.848,...,NaN,NaN,NaN,0,2.0500,NaN,NaN,0,24/07/2019 15:58,29/10/2021 12:59

In [19]:
# Elimina filas con más de 6 valores nulos
umbral = 6
df_filtrado = df[df.isnull().sum(axis=1) <= umbral]
df_filtrado.shape  # Muestra la nueva forma del DataFrame

(5144, 65)

In [ ]:
df_filtrado.isnull().sum() # Muestra la cantidad de valores nulos por columna después del filtrado

toi                   0
tid                   0
tfopwg_disp           0
rastr                 0
ra                    0
decstr                0
dec                   0
st_pmra               0
st_pmraerr1           0
st_pmraerr2           0
st_pmralim            0
st_pmdec              0
st_pmdecerr1          0
st_pmdecerr2          0
st_pmdeclim           0
pl_tranmid            0
pl_tranmiderr1        0
pl_tranmiderr2        0
pl_tranmidlim         0
pl_orbper             0
pl_orbpererr1         0
pl_orbpererr2         0
pl_orbperlim          0
pl_trandurh           0
pl_trandurherr1       0
pl_trandurherr2       0
pl_trandurhlim        0
pl_trandep            0
pl_trandeperr1        0
pl_trandeperr2        0
pl_trandeplim         0
pl_rade               0
pl_radeerr1           0
pl_radeerr2           0
pl_radelim            0
pl_insol              0
pl_insolerr1       5144
pl_insolerr2       5144
pl_insollim        5144
pl_eqt                0
pl_eqterr1         5144
pl_eqterr2         5144
pl_eqtlim          5144
st_tmag               0
st_tmagerr1           0
st_tmagerr2           0
st_tmaglim            0
st_dist               0
st_disterr1           0
st_disterr2           0
st_distlim            0
st_teff               0
st_tefferr1           0
st_tefferr2           0
st_tefflim            0
st_logg               0
st_loggerr1           0
st_loggerr2           0
st_logglim            0
st_rad                0
st_raderr1            0
st_raderr2            0
st_radlim             0
toi_created           0
rowupdate             0
dtype: int64

In [ ]:
df_filtrado = df_filtrado.drop(columns=[
    'pl_insolerr1', 'pl_insolerr2', 'pl_insollim', 
    'pl_eqterr1', 'pl_eqterr2', 'pl_eqtlim'
]) # Elimina columnas con muchos valores nulos

In [ ]:
df_filtrado.isnull().sum() # Muestra la cantidad de valores nulos por columna después de eliminación de columnas

toi                0
tid                0
tfopwg_disp        0
rastr              0
ra                 0
decstr             0
dec                0
st_pmra            0
st_pmraerr1        0
st_pmraerr2        0
st_pmralim         0
st_pmdec           0
st_pmdecerr1       0
st_pmdecerr2       0
st_pmdeclim        0
pl_tranmid         0
pl_tranmiderr1     0
pl_tranmiderr2     0
pl_tranmidlim      0
pl_orbper          0
pl_orbpererr1      0
pl_orbpererr2      0
pl_orbperlim       0
pl_trandurh        0
pl_trandurherr1    0
pl_trandurherr2    0
pl_trandurhlim     0
pl_trandep         0
pl_trandeperr1     0
pl_trandeperr2     0
pl_trandeplim      0
pl_rade            0
pl_radeerr1        0
pl_radeerr2        0
pl_radelim         0
pl_insol           0
pl_eqt             0
st_tmag            0
st_tmagerr1        0
st_tmagerr2        0
st_tmaglim         0
st_dist            0
st_disterr1        0
st_disterr2        0
st_distlim         0
st_teff            0
st_tefferr1        0
st_tefferr2        0
st_tefflim         0
st_logg            0
st_loggerr1        0
st_loggerr2        0
st_logglim         0
st_rad             0
st_raderr1         0
st_raderr2         0
st_radlim          0
toi_created        0
rowupdate          0
dtype: int64